name: create infrastructure on azure

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'infrastructure as code'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/networkproject_key.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          chmod 644 ~/.ssh/networkproject_key.pub

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        id: output
        run: |
          # قراءة القيم مباشرة بدون أي debug
          JUMP_IP=$(terraform output -raw jump_public_ip)
          LB_IP=$(terraform output -raw lb_public_ip)
          echo "jump_public_ip=$JUMP_IP" >> $GITHUB_OUTPUT
          echo "lb_public_ip=$LB_IP" >> $GITHUB_OUTPUT

      - name: Use Terraform Output
        run: |
          echo "Jump IP: ${{ steps.output.outputs.jump_public_ip }}"
          echo "LB IP: ${{ steps.output.outputs.lb_public_ip }}"
          



      